Project/CVdemo/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CVgenr.urls', namespace="CVpages"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/CVgenr/urls.py
from django.urls import path
from . import views

app_name = "CVpages"

urlpatterns = [
    path('button/', views.readcvbtn, name="button"),
    path('ogcreatehtml/', views.ogcreatehtml, name="ogcreatehtml"),
    path('updatecv/<str:pk>/', views.updatecv, name="updatecv"),
    path('deletecv/<str:pk>/', views.deleteCv, name="deletecv"),
    path('portfoloio/<str:pk>/', views.portfoloio, name="portfoloio"),

    path('pdfDown/<str:pk>/', views.render_pdf_view, name="pdfDown"),

]

Project/CVgenr/models.py
from email.headerregistry import Address
from email.policy import default
from tabnanny import verbose
from unicodedata import name
from django.db import models

from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField


#all models here.

class Cvdetails(models.Model):

    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True)
    description = models.TextField(null=True)
    your_title = models.CharField(max_length=500, blank=True, null=True)
    nic = models.CharField(max_length=20, null=True)
    # avatar = models.ImageField(null=True, default=n)
    date_of_birth = models.DateField(max_length=20, null=True)
    address = models.CharField(max_length=100, null=True)
    mobile_contact = models.CharField(max_length=10, null=True)
    home_contact = models.CharField(max_length=10, null=True)
    email = models.CharField(max_length=100, null=True)
    experience = models.TextField(null=True)
    skill1 = models.CharField(max_length=50, null=True)
    skill2 = models.CharField(max_length=50, null=True)
    skill3 = models.CharField(max_length=50, null=True)
    skill4 = models.CharField(max_length=50, null=True)
    skill5 = models.CharField(max_length=50, null=True)
    skill6 = models.CharField(max_length=50, null=True)
    education = models.TextField(null=True)
    # ol_result = models.CharField(max_length=100, null=True)
    # al_stream = models.CharField(max_length=100, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.first_name

Project/CVgenr/forms.py
from dataclasses import field
from pyexpat import model
from django.forms import ModelForm
from .models import Cvdetails

class CvDetailsForm(ModelForm):
    class Meta:
        model = Cvdetails
        fields = '__all__'

Project/CVgenr/views.py
import imp
from multiprocessing import context
from django.template import RequestContext
#from operator import mod
#from pyexpat import model
#from re import template
from django.shortcuts import render, redirect
from django.http import HttpResponse

#from django.views import generic
from django.contrib import messages
from .models import * 
from .forms import CvDetailsForm
from .filters import *

from django.template.loader import get_template
from xhtml2pdf import pisa



def readcvbtn(request):
    cvdata = Cvdetails.objects.all()

    cvfilter = CvFilter(request.GET, queryset=cvdata)
    cvdata = cvfilter.qs

    return render(request, 'CVpages/dil_preBtn.html', {'cvdata': cvdata , 'cvfilter':cvfilter })



def ogcreatehtml(request):

    form = CvDetailsForm()
    if request.method == 'POST':
        #print('',request.POST)
        form = CvDetailsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/button')

    context = {'form':form}
    return render(request, 'CVpages/dilcvcreate.html', context)


def updatecv(request, pk):

    cvdata = Cvdetails.objects.get(id=pk)
    form = CvDetailsForm(instance = cvdata)

    if request.method == 'POST':
        form = CvDetailsForm(request.POST, instance = cvdata)
        if form.is_valid():
            form.save()
            return redirect('/button')

    context = {'form':form}
    return render(request, 'CVpages/dilcvcreate.html', context)


def deleteCv(request, pk):
    cvdata = Cvdetails.objects.get(id=pk)

    if request.method == 'POST':
            cvdata.delete()
            return redirect('/button')


    context = {'form':cvdata}
    return render(request, 'CVpages/dilcvdiscard.html', context)


def portfoloio(request, pk):
    portfolio = Cvdetails.objects.get(id=pk)

    return render(request, 'CVpages/pdf1.html', {'cvdata': portfolio})


def render_pdf_view(request, pk):

    cvdata = Cvdetails.objects.get(id=pk)
    template_path = 'CVpages/pdf2.html'
    context = {'cvdata': cvdata }
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    # if download:
    response['Content-Disposition'] = 'attachment; filename="Resume.pdf"'
    # if display:
    # response['Content-Disposition'] = 'filename="Resume.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funny view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

Project/CVgenr/templates/CVpages/addons/footer.html
{% load static %}
<!-- ================================
Start Footer
================================= -->
<footer>
    <div class="footerCol">
    <div class="container">
        <ul class="socialCol">
        <li><a href="javascript:void(0)"><img src="{% static 'images/fb.svg' %}" alt="..."></a></li>
        <li><a href="javascript:void(0)"><img src="{% static 'images/insta.svg' %}" alt="..."></a></li>
        <li><a href="javascript:void(0)"><img src="{% static 'images/twitter.svg' %}" alt="..."></a></li>
        <li><a href="javascript:void(0)"><img src="{% static 'images/linkedin.svg' %}" alt="..."></a></li>
        </ul>
        <div class="copyrightCol">
        <p>Copyright ©{% now 'Y' %} All rights reserved. Designed by <a href="https://jamesgrangerdesign.co.uk/" target="_blank">James Granger Design</a></p>
        </div>
    </div>
    </div>
</footer>
<!-- ================================
End Footer
================================= -->

Project/CVgenr/templates/CVpages/addons/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}
    {% endfor %}
{% endif %}

Project/CVgenr/templates/CVpages/addons/nav.html
{% load static %}
<!-- ================================
Start Navigation Bar
================================= -->
<header>
    <div class="headerCol">
    <div class="container-fluid">
        <div class="row align-items-center">
        <div class="col-auto">
            {% comment %} <div class="logoCol"><a href="{% url 'CVpages:home' %}"><img src="{% static 'images/logo.png' %}" alt="..."></a></div> {% endcomment %}
        </div>
        <div class="col">
            <div class="d-md-none">
            <button class="navToggle">
                <span class="navToggle__text">Toggle Menu</span>
            </button>
            </div>
            <div class="navCollapseCol">
            <div class="navCol">
                <ul>
                {% comment %} <li><a href="{%url 'CVpages:home'%}">Home</a></li> {% endcomment %}
                <li><a href="{%url 'CVpages:portfolio_view' %}">Portfolio</a></li>
                {% comment %} <li><a href="{% url 'CVgenr:blogs' %}">Blog</a></li>
                <li><a href="{%url 'CVgenr:contact'%}">Contact</a></li> {% endcomment %}
                </ul>
            </div>
            </div>
        </div>
        </div>
    </div>
    </div>
</header>
<!-- ================================
End Navigation Bar
================================= -->

Project/CVgenr/templates/CVpages/dil_preBtn.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

</head>
<body>
    <div class="row">
        <div class="col">
            <center> 
                <h4><b> Ok, you have entered your Data ;) </b></h4>
            </center>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col">
                <div class="card- card-body">
    
                    <form method="GET">
                        {{cvfilter.form}}
                        <input type="submit" class="btn btn-primary" value="Search">
                    </form>
    
                </div>
            </div>
        </div>
    </div>
    

    {% comment %} <div class="d-grid gap-2 col-6 mx-auto">
        <button class="btn btn-primary" type="button">Preview</button>
        <button class="btn btn-primary" type="button">Edit</button>
        <button class="btn btn-primary" type="button">Discard</button>
    </div> {% endcomment %}
    <div class="container">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">NIC</th>
                    <th scope="col">Preview</th>
                    <th scope="col">Edit</th>
                    <th scope="col">Discard</th>
                </tr>
            </thead>

            {% for cvdata in cvdata %}
                <tr>
                    <td>{{cvdata.first_name}} {{cvdata.last_name}}</td>
                    <td>{{cvdata.nic}}</td>

                    <td><a class="btn btn-primary" href="{% url 'CVpages:portfoloio' cvdata.id %}">Preview</a></td>

                    <td><a class="btn btn-sm btn-info" href="{% url 'CVpages:updatecv' cvdata.id %}">Edit</a></td>

                    <td><a class="btn btn-sm btn-info" href="{% url 'CVpages:deletecv' cvdata.id %}">Discard</a></td> 

                </tr>

            {% endfor %}

        </table>

    </div>

    
</body>
</html>

Project/CVgenr/templates/CVpages/dilcvcreate.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CV Create Form</title>

    <style>
        *{
            margin: 5px;
            padding: 5px;
        }
        
        .container{
            width: 60%;
            border: 1px solid;
        }
    </style>
</head>
<body>
    <div class="row">
        <div class="col">
            <center> 
                <h4><b> Insert your Details </b></h4>
            </center>
        </div>
    </div>

    <div class="container">
        <form action="" method="POST">

            {% csrf_token %}
            {{form.as_p}}

            {% comment %} <div class="col-10">
                <label for="formGroupExampleInput" class="form-label">Name</label>
                <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Example input placeholder">
            </div>
            <div class="col-md-6">
                <label for="formGroupExampleInput2" class="form-label">Birthday</label>
                <input type="date" class="form-control" id="formGroupExampleInput2" placeholder="Another input placeholder">
            </div>
            <div class="col-10">
                <label for="formGroupExampleInput3" class="form-label">Address</label>
                <input type="text" class="form-control" id="formGroupExampleInput3" placeholder="Example input placeholder">
            </div>
            <div class="col-4">
                <label for="formGroupExampleInput4" class="form-label">Contact</label>
                <input type="text" class="form-control" id="formGroupExampleInput4" placeholder="Another input placeholder">
            </div>
            <div class="col-4">
                <label for="formGroupExampleInput5" class="form-label">House Contact</label>
                <input type="text" class="form-control" id="formGroupExampleInput5" placeholder="Example input placeholder">
            </div>
            <div class="col-10">
                <label for="formGroupExampleInput6" class="form-label">Email</label>
                <input type="Email" class="form-control" id="formGroupExampleInput6" placeholder="Another input placeholder">
            </div>
            <div class="col-10">
                <label class="formGroupExampleInput10">Experience</label>
                <textarea class="form-control" aria-label="With textarea" id="formGroupExampleInput10"></textarea>
            </div>
            <div class="col-6">
                <label for="formGroupExampleInput12" class="form-label">OL Results</label>
                <input type="text" class="form-control" id="formGroupExampleInput12" placeholder="Another input placeholder">
            </div>
            <div class="col-6">
                <label for="formGroupExampleInput13" class="form-label">AL Subject Stream</label>
                <input type="text" class="form-control" id="formGroupExampleInput13" placeholder="Another input placeholder">
            </div>

            <div class="col-10">
                <label for="formGroupExampleInput17" class="form-label">Skill</label>
                <textarea class="form-control" aria-label="With textarea" id="formGroupExampleInput17"></textarea>
            </div> {% endcomment %}
    
            <input type="submit" name="Submit" value="Send CV details" class="btn btn-primary">
        </form>
    </div>

    <script>
        //Query All input fields
        var form_fields = document.getElementsByTagName('input')
        form_fields[1].placeholder='First Name..';
        form_fields[2].placeholder='Last Name..';
        {% comment %} form_fields[3].placeholder='About your self..'; {% endcomment %}
        form_fields[3].placeholder='ect: Web Developer | DevOp..';
        form_fields[4].placeholder='Your NIC or Passport ID';
        form_fields[5].placeholder='Date of Birth';
        form_fields[6].placeholder='Address';
        form_fields[7].placeholder='Mobile Contact';
        form_fields[8].placeholder='Home Contact';
        form_fields[9].placeholder='example@mail.com';
        {% comment %} form_fields[11].placeholder='I worked with..... from 2019 - 2022'; {% endcomment %}
        form_fields[10].placeholder='Your tech or language skill';
        form_fields[11].placeholder='Your tech or language skill';
        form_fields[12].placeholder='Your tech or language skill';
        form_fields[13].placeholder='Your tech or language skill';
        form_fields[14].placeholder='Your tech or language skill';
        form_fields[15].placeholder='Your tech or language skill';


        for (var field in form_fields){	
            form_fields[field].className += ' form-control'
        }
    </script>

    
</body>
</html>

Project/CVgenr/templates/CVpages/dilcvdiscard.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

</head>
<body>
    <div class="row">
        <div class="col">
            <center> 
                
                <h4><b> Are you sure you need to delete your CV </b></h4>
            </center>
        </div>
    </div>

    <div class="container">
        <form method="POST">
            {% csrf_token %}
            <input name="delete" class="btn btn-sm btn-danger" type="submit" value="Delete">
            <a href="{% url 'CVpages:button' %}">Cancel</a>
        </form>

    </div>

    
</body>
</html>

Project/CVgenr/templates/CVpages/pdf1.html
{% load static %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>

	<title>{{cvdata.first_name}} | {{cvdata.your_title}} | FlexIT.lk</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />

	<meta name="keywords" content="" />
	<meta name="description" content="" />

	<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.7.0/build/reset-fonts-grids/reset-fonts-grids.css" media="all" /> 
	<link rel="stylesheet" href="{% static '/css/resume.css' %}">

</head>
<body>

<div id="doc2" class="yui-t7">
	<div id="inner">
	
		<div id="hd">
			<div class="yui-gc">
				<div class="yui-u first">
					<h1>{{cvdata.first_name}} {{cvdata.last_name}}</h1>
					<h2>{{cvdata.your_title}}</h2>
				</div>

				<div class="yui-u">
					<div class="contact-info">
						<h3><a id="pdf" href="{% url 'CVpages:pdfDown' cvdata.id %}">Download PDF</a></h3>
						<h3><a href="mailto:{{cvdata.email}}">{{cvdata.email}}</a></h3>
						<h3>{{cvdata.mobile_contact}}</h3>
					</div><!--// .contact-info -->
				</div>
			</div><!--// .yui-gc -->
		</div><!--// hd -->

		<div id="bd">
			<div id="yui-main">
				<div class="yui-b">

					<div class="yui-gf">
						<div class="yui-u first">
							<h2>Profile</h2>
						</div>
						<div class="yui-u">
							<p class="enlarge">
								{{cvdata.description}} 
							</p>
						</div>
					</div><!--// .yui-gf -->

					{% comment %} <div class="yui-gf">
						<div class="yui-u first">
							<h2>Skills</h2>
						</div>
						<div class="yui-u">

								<div class="talent">
									<h2>Web Design</h2>
									<p>Assertively exploit wireless initiatives rather than synergistic core competencies.	</p>
								</div>

								<div class="talent">
									<h2>Interface Design</h2>
									<p>Credibly streamline mission-critical value with multifunctional functionalities.	 </p>
								</div>

								<div class="talent">
									<h2>Project Direction</h2>
									<p>Proven ability to lead and manage a wide variety of design and development projects in team and independent situations.</p>
								</div>
						</div>
					</div><!--// .yui-gf --> {% endcomment %}

					<div class="yui-gf">
						<div class="yui-u first">
							<h2>Technical</h2>
						</div>
						<div class="yui-u">
							<ul class="talent">
								<li>{{cvdata.skill1}}</li>
								<li>{{cvdata.skill2}}</li>
								<li class="last">{{cvdata.skill3}}</li>
							</ul>

							<ul class="talent">
								<li>{{cvdata.skill4}}</li>
								<li>{{cvdata.skill5}}</li>
								<li class="last">{{cvdata.skill6}}</li>
							</ul>

							<ul class="talent">
								<li></li>
								<li></li>
								<li class="last"></li>
							</ul>
						</div>
					</div><!--// .yui-gf-->

					<div class="yui-gf">
	
						<div class="yui-u first">
							<h2>Experience</h2>
						</div><!--// .yui-u -->

						<div class="yui-u">

							<div class="job">
								{{cvdata.experience|linebreaks}}
								{% comment %} <h2>Facebook</h2>
								<h3>Senior Interface Designer</h3>
								<h4>2005-2007</h4>
								<p>Intrinsicly enable optimal core competencies through corporate relationships. Phosfluorescently implement worldwide vortals and client-focused imperatives. Conveniently initiate virtual paradigms and top-line convergence. </p> {% endcomment %}
							</div>

							{% comment %} <div class="job">
								<h2>Apple Inc.</h2>
								<h3>Senior Interface Designer</h3>
								<h4>2005-2007</h4>
								<p>Progressively reconceptualize multifunctional "outside the box" thinking through inexpensive methods of empowerment. Compellingly morph extensive niche markets with mission-critical ideas. Phosfluorescently deliver bricks-and-clicks strategic theme areas rather than scalable benefits. </p>
							</div> {% endcomment %}

							{% comment %} <div class="job">
								<h2>Microsoft</h2>
								<h3>Principal and Creative Lead</h3>
								<h4>2004-2005</h4>
								<p>Intrinsicly transform flexible manufactured products without excellent intellectual capital. Energistically evisculate orthogonal architectures through covalent action items. Assertively incentivize sticky platforms without synergistic materials. </p>
							</div> {% endcomment %}


							{% comment %} <div class="job last">
								<h2>International Business Machines (IBM)</h2>
								<h3>Lead Web Designer</h3>
								<h4>2001-2004</h4>
								<p>Globally re-engineer cross-media schemas through viral methods of empowerment. Proactively grow long-term high-impact human capital and highly efficient innovation. Intrinsicly iterate excellent e-tailers with timely e-markets.</p>
							</div> {% endcomment %}

						</div><!--// .yui-u -->
					</div><!--// .yui-gf -->


					<div class="yui-gf last">
						<div class="yui-u first">
							<h2>Education</h2>
						</div>
						<div class="yui-u">
							{{cvdata.education|linebreaks}}
							{% comment %} <h2>Indiana University - Bloomington, Indiana</h2>
							<h3>Dual Major, Economics and English &mdash; <strong>4.0 GPA</strong> </h3> {% endcomment %}
						</div>
					</div><!--// .yui-gf -->


				</div><!--// .yui-b -->
			</div><!--// yui-main -->
		</div><!--// bd -->

		<div id="ft">
			<p>{{cvdata.first_name}} {{cvdata.last_name}} &mdash; <a href="mailto:{{cvdata.email}}">{{cvdata.email}}</a> &mdash; {{cvdata.mobile_contact}}, {{cvdata.home_contact}}</p>
		</div><!--// footer -->

	</div><!-- // inner -->


</div><!--// doc -->


</body>
</html>

Project/CVgenr/templates/CVpages/pdf2.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

     <title>{{cvdata.first_name}} | {{cvdata.your_title}} | FlexIT.lk</title>

     <style type="text/css">
        * { margin: 0; padding: 0; }
        body { font: 16px Helvetica, Sans-Serif; line-height: 24px; }
        .clear { clear: both; }
        #page-wrap { width: 1000px; margin: 40px auto 60px; }
        #pic { float: right; margin: -30px 0 0 0; height: 100px}
        h1 { margin: 0 0 16px 0; padding: 0 0 16px 0; font-size: 42px; font-weight: bold; letter-spacing: -2px; border-bottom: 1px solid #999; }
        h2 { font-size: 20px; margin: 0 0 6px 0; position: relative; }
        h2 span { position: absolute; bottom: 0; right: 0; font-style: italic; font-family: Georgia, Serif; font-size: 16px; color: #999; font-weight: normal; }
        p { margin: 0 0 16px 0; }
        a { color: #999; text-decoration: none; border-bottom: 1px dotted #999; }
        a:hover { border-bottom-style: solid; color: black; }
        ul { margin: 0 0 32px 17px; list-style: none; }
        #objective { width: 500px; float: left; }
        #objective p { font-family: Georgia, Serif; font-style: italic; color: #666; }
        dt { font-style: italic; font-weight: bold; font-size: 20px; text-align: left; padding: 0 26px 0 0; width: 15px; float: left; height: 100px; }
        dd { width: 600px; float: right; }
        dd.clear { float: none; margin: 0; height: 15px; }
     </style>
</head>

<body>

    <div id="page-wrap">
    
        {% comment %} <img src="{{cvdata.avatar}}" alt="Photo of Cthulu" id="pic"> {% endcomment %}
    
        <div id="contact-info" class="vcard">
        
            <!-- Microformats! -->
        
            <h1 class="fn">{{cvdata.first_name}} {{cvdata.last_name}}</h1>
        
            <p>
                Cell: <span class="tel">{{cvdata.mobile_contact}}, {{cvdata.home_contact}}</span><br />
                Email: <a class="email" href="mailto:{{cvdata.email}}">{{cvdata.email}}</a>
            </p>
        </div>
                
        <div id="objective">
            <p>
                {{cvdata.description}}
            </p>
        </div>
        
        <div class="clear"></div>
        
        <dl>
            <dd class="clear"></dd>
            
            <dt>Education&nbsp;:-</dt>
            <dd>
                <h4>{{cvdata.education |linebreaks}}</h4>
            </dd>
            
            <dd class="clear"></dd>
            
            <dt>Skills&nbsp;:-</dt>
            <dd>
                <ul>
                    <li>{{cvdata.skill1}}</li>
                    <li>{{cvdata.skill2}}</li>
                    <li>{{cvdata.skill3}}</li>
                    <li>{{cvdata.skill4}}</li>
                    <li>{{cvdata.skill5}}</li>
                    <li>{{cvdata.skill6}}</li>
                </ul>
            </dd>
            
            <dd class="clear"></dd>
            
            <dt>Experience&nbsp;:-</dt><br>
            <dd>
                <h4>{{cvdata.experience |linebreaks}}</h4>
            </dd>
            
            <dd class="clear"></dd>
            
            {% comment %} <dt>Hobbies</dt>
            <dd>World Domination, Deep Sea Diving, Murder Most Foul</dd> {% endcomment %}
            
            {% comment %} <dd class="clear"></dd> {% endcomment %}
            
            <dt>References</dt>
            <dd>&nbsp;Available on request</dd>
            
            <dd class="clear"></dd>
        </dl>
        
        <div class="clear"></div>
    
    </div>

</body>

</html>

Project/CVgenr/templates/CVpages/trial.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CV detail gather</title>

</head>
<body>
    <div class="row">
        <div class="col">
            <center> 
                <h4><b> Registration </b></h4>
            </center>
        </div>
    </div>

    <form action="" method="POST" class="row g-3">

        {% csrf_token %}
        {{form.as_p}}

        <input type="submit" name="Submit" value="Send CV details">

    </form>

    <script>
            
        //Query All input fields
        var form_fields = document.getElementsByTagName('input')
        form_fields[1].placeholder='Username..';
        form_fields[2].placeholder='example@email.com..';
        form_fields[3].placeholder='1234 Main Street...';
        form_fields[4].placeholder='';


        for (var field in form_fields){	
            form_fields[field].className += ' form-control'
        }
    </script>

    
</body>
</html>